------------------------------------------------------------
-- HRM DATABASE FULL SCRIPT
-- Oracle Database - Project Quản lý nhân sự
-- User/schema: HRM
-- PDB: ORCL21PDB1
------------------------------------------------------------

------------------------------------------------------------
-- 0. CLEAN OLD TABLES AND SEQUENCES
------------------------------------------------------------

DROP TABLE LEAVE_REQUESTS CASCADE CONSTRAINTS PURGE;
DROP TABLE SALARIES CASCADE CONSTRAINTS PURGE;
DROP TABLE ATTENDANCES CASCADE CONSTRAINTS PURGE;
DROP TABLE EMPLOYEES CASCADE CONSTRAINTS PURGE;
DROP TABLE DEPARTMENTS CASCADE CONSTRAINTS PURGE;
DROP TABLE USERS CASCADE CONSTRAINTS PURGE;

DROP SEQUENCE LEAVE_REQUESTS_SEQ;
DROP SEQUENCE SALARIES_SEQ;
DROP SEQUENCE ATTENDANCES_SEQ;
DROP SEQUENCE EMPLOYEES_SEQ;
DROP SEQUENCE DEPARTMENTS_SEQ;
DROP SEQUENCE USERS_SEQ;

------------------------------------------------------------
-- 1. TABLE USERS
------------------------------------------------------------

CREATE TABLE USERS (
    ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    ROLE_NAME VARCHAR2(20),
    STATUS NUMBER(1)
);

CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1;

------------------------------------------------------------
-- 2. TABLE DEPARTMENTS
------------------------------------------------------------

CREATE TABLE DEPARTMENTS (
    ID NUMBER PRIMARY KEY,
    NAME NVARCHAR2(100) NOT NULL,
    DESCRIPTION NVARCHAR2(255)
);

CREATE SEQUENCE DEPARTMENTS_SEQ START WITH 1 INCREMENT BY 1;

------------------------------------------------------------
-- 3. TABLE EMPLOYEES
------------------------------------------------------------

CREATE TABLE EMPLOYEES (
    ID NUMBER PRIMARY KEY,
    FULL_NAME NVARCHAR2(100) NOT NULL,
    EMAIL NVARCHAR2(100),
    PHONE VARCHAR2(20),
    GENDER VARCHAR2(10),
    DATE_OF_BIRTH DATE,
    ADDRESS NVARCHAR2(255),
    POSITION_NAME NVARCHAR2(100),
    SALARY_BASE NUMBER(12,2),
    DEPARTMENT_ID NUMBER,
    USER_ID NUMBER,

    CONSTRAINT FK_EMPLOYEE_DEPARTMENT
        FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENTS(ID),

    CONSTRAINT FK_EMPLOYEE_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(ID)
);

CREATE SEQUENCE EMPLOYEES_SEQ START WITH 1 INCREMENT BY 1;

------------------------------------------------------------
-- 4. TABLE ATTENDANCES
------------------------------------------------------------

CREATE TABLE ATTENDANCES (
    ID NUMBER PRIMARY KEY,
    EMPLOYEE_ID NUMBER NOT NULL,
    CHECK_IN_TIME TIMESTAMP,
    CHECK_OUT_TIME TIMESTAMP,
    WORK_DATE DATE,
    STATUS_NAME VARCHAR2(20),

    CONSTRAINT FK_ATTENDANCE_EMPLOYEE
        FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEES(ID)
);

CREATE SEQUENCE ATTENDANCES_SEQ START WITH 1 INCREMENT BY 1;

------------------------------------------------------------
-- 5. TABLE SALARIES
------------------------------------------------------------

CREATE TABLE SALARIES (
    ID NUMBER PRIMARY KEY,
    EMPLOYEE_ID NUMBER NOT NULL,
    SALARY_MONTH NUMBER NOT NULL,
    SALARY_YEAR NUMBER NOT NULL,
    BASE_SALARY NUMBER(12,2),
    BONUS NUMBER(12,2),
    DEDUCTION NUMBER(12,2),
    TOTAL_SALARY NUMBER(12,2),

    CONSTRAINT FK_SALARY_EMPLOYEE
        FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEES(ID)
);

CREATE SEQUENCE SALARIES_SEQ START WITH 1 INCREMENT BY 1;

------------------------------------------------------------
-- 6. TABLE LEAVE_REQUESTS
------------------------------------------------------------

CREATE TABLE LEAVE_REQUESTS (
    ID NUMBER PRIMARY KEY,
    EMPLOYEE_ID NUMBER NOT NULL,
    START_DATE DATE,
    END_DATE DATE,
    REASON_TEXT NVARCHAR2(500),
    STATUS_NAME VARCHAR2(20),

    CONSTRAINT FK_LEAVE_EMPLOYEE
        FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEES(ID)
);

CREATE SEQUENCE LEAVE_REQUESTS_SEQ START WITH 1 INCREMENT BY 1;

------------------------------------------------------------
-- 7. INSERT USERS
------------------------------------------------------------

INSERT INTO USERS (ID, USERNAME, PASSWORD, ROLE_NAME, STATUS)
VALUES (USERS_SEQ.NEXTVAL, 'admin', '123456', 'ADMIN', 1);

INSERT INTO USERS (ID, USERNAME, PASSWORD, ROLE_NAME, STATUS)
VALUES (USERS_SEQ.NEXTVAL, 'hr01', '123456', 'HR', 1);

INSERT INTO USERS (ID, USERNAME, PASSWORD, ROLE_NAME, STATUS)
VALUES (USERS_SEQ.NEXTVAL, 'employee01', '123456', 'EMPLOYEE', 1);

INSERT INTO USERS (ID, USERNAME, PASSWORD, ROLE_NAME, STATUS)
VALUES (USERS_SEQ.NEXTVAL, 'employee02', '123456', 'EMPLOYEE', 1);

------------------------------------------------------------
-- 8. INSERT DEPARTMENTS
------------------------------------------------------------

INSERT INTO DEPARTMENTS (ID, NAME, DESCRIPTION)
VALUES (DEPARTMENTS_SEQ.NEXTVAL, N'Phòng IT', N'Phòng công nghệ thông tin');

INSERT INTO DEPARTMENTS (ID, NAME, DESCRIPTION)
VALUES (DEPARTMENTS_SEQ.NEXTVAL, N'Phòng Nhân Sự', N'Quản lý nhân viên');

INSERT INTO DEPARTMENTS (ID, NAME, DESCRIPTION)
VALUES (DEPARTMENTS_SEQ.NEXTVAL, N'Phòng Kế Toán', N'Quản lý tài chính');

------------------------------------------------------------
-- 9. INSERT EMPLOYEES
------------------------------------------------------------

INSERT INTO EMPLOYEES (
    ID, FULL_NAME, EMAIL, PHONE, GENDER, DATE_OF_BIRTH,
    ADDRESS, POSITION_NAME, SALARY_BASE, DEPARTMENT_ID, USER_ID
)
VALUES (
    EMPLOYEES_SEQ.NEXTVAL, N'Nguyễn Văn A', 'a@gmail.com',
    '0900000001', 'MALE', TO_DATE('2000-01-01', 'YYYY-MM-DD'),
    N'Hà Nội', N'Java Backend Intern', 8000000, 1, 1
);

INSERT INTO EMPLOYEES (
    ID, FULL_NAME, EMAIL, PHONE, GENDER, DATE_OF_BIRTH,
    ADDRESS, POSITION_NAME, SALARY_BASE, DEPARTMENT_ID, USER_ID
)
VALUES (
    EMPLOYEES_SEQ.NEXTVAL, N'Trần Thị B', 'b@gmail.com',
    '0900000002', 'FEMALE', TO_DATE('1999-05-10', 'YYYY-MM-DD'),
    N'Hồ Chí Minh', N'HR Staff', 12000000, 2, 2
);

INSERT INTO EMPLOYEES (
    ID, FULL_NAME, EMAIL, PHONE, GENDER, DATE_OF_BIRTH,
    ADDRESS, POSITION_NAME, SALARY_BASE, DEPARTMENT_ID, USER_ID
)
VALUES (
    EMPLOYEES_SEQ.NEXTVAL, N'Lê Văn C', 'c@gmail.com',
    '0900000003', 'MALE', TO_DATE('1998-03-20', 'YYYY-MM-DD'),
    N'Đà Nẵng', N'Frontend Developer', 15000000, 1, 3
);

INSERT INTO EMPLOYEES (
    ID, FULL_NAME, EMAIL, PHONE, GENDER, DATE_OF_BIRTH,
    ADDRESS, POSITION_NAME, SALARY_BASE, DEPARTMENT_ID, USER_ID
)
VALUES (
    EMPLOYEES_SEQ.NEXTVAL, N'Phạm Thị D', 'd@gmail.com',
    '0900000004', 'FEMALE', TO_DATE('1997-08-15', 'YYYY-MM-DD'),
    N'Cần Thơ', N'Accountant', 14000000, 3, 4
);

------------------------------------------------------------
-- 10. INSERT ATTENDANCES
------------------------------------------------------------

INSERT INTO ATTENDANCES (
    ID, EMPLOYEE_ID, CHECK_IN_TIME, CHECK_OUT_TIME, WORK_DATE, STATUS_NAME
)
VALUES (
    ATTENDANCES_SEQ.NEXTVAL, 1,
    TO_TIMESTAMP('2026-05-31 08:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_TIMESTAMP('2026-05-31 17:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_DATE('2026-05-31', 'YYYY-MM-DD'),
    'PRESENT'
);

INSERT INTO ATTENDANCES (
    ID, EMPLOYEE_ID, CHECK_IN_TIME, CHECK_OUT_TIME, WORK_DATE, STATUS_NAME
)
VALUES (
    ATTENDANCES_SEQ.NEXTVAL, 2,
    TO_TIMESTAMP('2026-05-31 08:15:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_TIMESTAMP('2026-05-31 17:05:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_DATE('2026-05-31', 'YYYY-MM-DD'),
    'LATE'
);

INSERT INTO ATTENDANCES (
    ID, EMPLOYEE_ID, CHECK_IN_TIME, CHECK_OUT_TIME, WORK_DATE, STATUS_NAME
)
VALUES (
    ATTENDANCES_SEQ.NEXTVAL, 3,
    TO_TIMESTAMP('2026-05-31 07:55:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_TIMESTAMP('2026-05-31 17:10:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_DATE('2026-05-31', 'YYYY-MM-DD'),
    'PRESENT'
);

------------------------------------------------------------
-- 11. INSERT SALARIES
------------------------------------------------------------

INSERT INTO SALARIES (
    ID, EMPLOYEE_ID, SALARY_MONTH, SALARY_YEAR,
    BASE_SALARY, BONUS, DEDUCTION, TOTAL_SALARY
)
VALUES (
    SALARIES_SEQ.NEXTVAL, 1, 5, 2026,
    8000000, 1000000, 500000, 8500000
);

INSERT INTO SALARIES (
    ID, EMPLOYEE_ID, SALARY_MONTH, SALARY_YEAR,
    BASE_SALARY, BONUS, DEDUCTION, TOTAL_SALARY
)
VALUES (
    SALARIES_SEQ.NEXTVAL, 2, 5, 2026,
    12000000, 2000000, 300000, 13700000
);

INSERT INTO SALARIES (
    ID, EMPLOYEE_ID, SALARY_MONTH, SALARY_YEAR,
    BASE_SALARY, BONUS, DEDUCTION, TOTAL_SALARY
)
VALUES (
    SALARIES_SEQ.NEXTVAL, 3, 5, 2026,
    15000000, 1500000, 700000, 15800000
);

------------------------------------------------------------
-- 12. INSERT LEAVE REQUESTS
------------------------------------------------------------

INSERT INTO LEAVE_REQUESTS (
    ID, EMPLOYEE_ID, START_DATE, END_DATE, REASON_TEXT, STATUS_NAME
)
VALUES (
    LEAVE_REQUESTS_SEQ.NEXTVAL, 1,
    TO_DATE('2026-06-01', 'YYYY-MM-DD'),
    TO_DATE('2026-06-02', 'YYYY-MM-DD'),
    N'Nghỉ việc cá nhân',
    'PENDING'
);

INSERT INTO LEAVE_REQUESTS (
    ID, EMPLOYEE_ID, START_DATE, END_DATE, REASON_TEXT, STATUS_NAME
)
VALUES (
    LEAVE_REQUESTS_SEQ.NEXTVAL, 2,
    TO_DATE('2026-06-05', 'YYYY-MM-DD'),
    TO_DATE('2026-06-06', 'YYYY-MM-DD'),
    N'Nghỉ ốm',
    'APPROVED'
);

COMMIT;

------------------------------------------------------------
-- 13. CHECK DATA
------------------------------------------------------------

SELECT * FROM USERS;
SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;
SELECT * FROM ATTENDANCES;
SELECT * FROM SALARIES;
SELECT * FROM LEAVE_REQUESTS;
